
when:
  - event: push

steps:
  - name: prepare_test
    image: alpine:latest
    commands:
      - apk add --no-cache bash
      - apk add --no-cache git
      - git submodule add https://github.com/bats-core/bats-core.git test/bats
      - git submodule add https://github.com/bats-core/bats-support.git test/test_helper/bats-support
      - git submodule add https://github.com/bats-core/bats-assert.git test/test_helper/bats-assert
  - name: test
    image: bats/bats:latest
    commands:
      - bats test/test.bats